---
# dnf install packages

- name: Setup Fedora workstation
  hosts: localhost
  become: true

  tasks:

    ## add dnf proxy
    - name: Add dnf proxy
      ansible.builtin.lineinfile:
        path: /etc/dnf/dnf.conf
        regexp: '^proxy='
        line: 'proxy=http://10.10.10.100:3142'

    ## optimize dnf settings
    - name: DNF set fastest mirror
      ansible.builtin.lineinfile:
        path: /etc/dnf/dnf.conf
        regexp: '^fastestmirror='
        line: 'fastestmirror=true'
      notify: restart dnf

    - name: DNF set max parallel downloads
      ansible.builtin.lineinfile:
        path: /etc/dnf/dnf.conf
        regexp: '^max_parallel_downloads='
        line: 'max_parallel_downloads=10'
      notify: restart dnf

    - name: DNF set deltarpm
      ansible.builtin.lineinfile:
        path: /etc/dnf/dnf.conf
        regexp: '^deltarpm='
        line: 'deltarpm=true'
      notify: restart dnf

    ###### The following imports repo keys for RPM Fusion
    - name: Importing RPM Fusion (free) key
      become: true
      ansible.builtin.rpm_key:
        state: present
        key: https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-free-fedora-2020

    - name: Importing RPM (non-free) key
      become: true
      ansible.builtin.rpm_key:
        state: present
        key: https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-nonfree-fedora-2020

    ###### The following installs the RPM Fusion repos
    - name: Remote RPM install for RPM Fusion nonfree repo
      become: true
      ansible.builtin.dnf:
        name: https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}.noarch.rpm
        state: present
      when: ansible_distribution == 'Fedora'

    - name: Remote RPM install for RPM Fusion free repo
      become: true
      ansible.builtin.dnf:
        name: https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm
        state: present
      when: ansible_distribution == 'Fedora'

    ###### The following installs the VS Code repo
    - name: Add VS Code repo
      ansible.builtin.yum_repository:
        name: code
        baseurl: https://packages.microsoft.com/yumrepos/vscode
        state: present
        description: Visual Studio Code
        gpgcheck: true
        gpgkey: https://packages.microsoft.com/keys/microsoft.asc

    # remove applications conflicting with installation of ffmpeg full version

    - name: Remove libswscale-free
      become: true
      ansible.builtin.dnf:
        name: libswscale-free
        state: absent

    - name: Remove libswresample-free
      become: true
      ansible.builtin.dnf:
        name: libswresample-free
        state: absent

    - name: Remove libavutil-free
      become: true
      ansible.builtin.dnf:
        name: libavutil-free
        state: absent

    # procede to install packages

    - name: DNF | Install packages
      ansible.builtin.dnf:
        name:
          - tmux
          - exa
          - bat
          - git
          - wget
          - iperf3
          - mc
          - htop
          - ncdu
          - python3
          - python3-pip
          - curl
          - stow
          - zsh
          - neofetch
          - intel-media-driver
          - bpytop
          - ckb-next
          # codecs
          - ffmpeg
          # proprietary
          - dropbox
          - megasync
          - dolphin-megasync
          - code # VS Code
        state: present
        update_cache: true
