---
# dnf install packages

- name: Setup Fedora workstation
  hosts: localhost
  become: true

  tasks:

    - name: DNF | Install RPM Fusion
      ansible.builtin.dnf:
        name: rpmfusion-free-release-tainted rpmfusion-nonfree-release-tainted
        state: present
      when: ansible_distribution == 'Fedora'

    - name: Enable the RPM Fusion free repository
      ansible.builtin.dnf:
        name: "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm"
        state: present
      when: ansible_distribution == 'Fedora'

    - name: Enable the RPM Fusion nonfree repository
      ansible.builtin.dnf:
        name: "https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}.noarch.rpm"
        state: present
      when: ansible_distribution == 'Fedora'

    - name: Add VS Code repo
      ansible.builtin.yum_repository:
        name: Visual Studio Code
        baseurl: https://packages.microsoft.com/yumrepos/vscode
        state: present
        description: Visual Studio Code
        gpgcheck: true
        gpgkey: https://packages.microsoft.com/keys/microsoft.asc

    - name: DNF | Install terminal packages
      ansible.builtin.dnf:
        name:
          - tmux
          - exa
          - bat
          - git
          - wget
          - iperf3
          - mc
          - htop
          - ncdu
          - python3
          - python3-pip
          - curl
          - stow
          - zsh
          - neofetch
          - intel-media-driver
          - bpytop
          - ckb-next
          # codes
          - ffmpeg
          # proprietary
          - dropbox
          - megasync
          - dolphin-megasync
          - code # VS Code
        state: present
        update_cache: true
